---
title: "Analysis of IRT experiment"
author: "Sebastian Schuster"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
theme_set(theme_bw())


binomial_smooth <- function(...) {
  geom_smooth(method = "glm", method.args = list(family = "binomial"), ...)
}

```

```{r load_data, fig.height=15, fig.width=10}

d.some = read.csv("../../data/5_irt_no_prior///5_irt_no_prior-cond2-trials.csv")
d.many = read.csv("../../data/5_irt_no_prior//5_irt_no_prior-cond3-trials.csv")
d.many$workerid = d.many$workerid +  max(d.some$workerid) + 1
d = rbind(d.some, d.many) %>% 
  filter(block > 0) %>%
  rename(condition = Answer.condition) %>% 
  mutate(ambiguity_type = recode_factor(
    type, 
         `75_100_1` = "filler",
         `75_100_2` = "filler",
         `90_0_1` = "filler",
         `90_0_2` = "filler",
         `25_100_1` = "filler",
         `25_100_2` = "filler",
         `40_0_1` = "filler",
         `40_0_2` = "filler",
         `25_50_1` = "25_50_1_critical",
         `25_50_2` = "25_50_2_critical",
         `50_90_1` = "50_90_1_critical",
         `50_90_2` = "50_90_2_critical",
         .default = "filler",
         .ordered = T),
    trial_type = recode_factor(
    type, 
         `75_100_1` = "q1_filler",
         `75_100_2` = "all_filler",
         `90_0_1` = "q2_filler",
         `90_0_2` = "none_filler",
         `25_100_1` = "q1_filler",
         `25_100_2` = "all_filler",
         `40_0_1` = "q2_filler",
         `40_0_2` = "none_filler",
         `25_50_1` = "25_50_1_critical",
         `25_50_2` = "25_50_2_critical",
         `50_90_1` = "50_90_1_critical",
         `50_90_2` = "50_90_2_critical",
          .default = "all_filler",
         .ordered = T)) %>%
    mutate(half=if_else(block < 5, 0, 1)) %>%
    filter(condition != "many_most")

exclude_workerids = d %>% filter(utterance_label == "color") %>% filter(label == "target") %>%
  group_by(workerid) %>% summarise(p=mean(clicked)) %>% filter(p < 0.9) %>% .$workerid

excluded_bonus = d %>% filter(utterance_label == "color") %>% filter(label == "target") %>%
  group_by(workerid, Answer.bonus) %>% summarise(p=mean(clicked))


d = d %>% filter(!(workerid %in% exclude_workerids))


```




```{r indiv_plots, fig.width=10, fig.height = 15} 


d %>% 
  filter(utterance_label == "quantifier") %>% 
  filter(label == "target") %>% 
  group_by(half,condition,trial_type,quantifier,ambiguity_type, workerid) %>% 
  summarise(p_w = mean(clicked)) %>%
  group_by(half,condition,trial_type,quantifier,ambiguity_type) %>%
  summarise(p = mean(p_w), low = ci.low(p_w), high=ci.high(p_w)) %>%
  ggplot(aes(x=half, y=p)) + geom_bar(stat="identity") + facet_wrap(~condition + trial_type + quantifier + ambiguity_type ) + 
  geom_point(col="#cc3333", alpha=.2, data = d %>% 
  filter(utterance_label == "quantifier") %>% 
  filter(label == "target") %>% 
  mutate(half=if_else(block < 5, 0, 1)) %>% 
  group_by(half,workerid,condition,trial_type,quantifier,ambiguity_type) %>% 
  summarise(p = mean(clicked))) + geom_errorbar(aes(ymin=p-low, ymax=p+high))

d %>% 
  filter(utterance_label == "color") %>% 
  filter(label == "target") %>% 
  group_by(half,condition,trial_type,quantifier,ambiguity_type, workerid) %>% 
  summarise(p_w = mean(clicked)) %>%
  group_by(half,condition,trial_type,quantifier,ambiguity_type) %>%
  summarise(p = mean(p_w), low = ci.low(p_w), high=ci.high(p_w)) %>%
  ggplot(aes(x=half, y=p)) + geom_bar(stat="identity") + facet_wrap(~condition + trial_type + quantifier + ambiguity_type ) + 
  geom_point(col="#cc3333", alpha=.2, data = d %>% 
  filter(utterance_label == "color") %>% 
  filter(label == "target") %>% 
  mutate(half=if_else(block < 5, 0, 1)) %>% 
  group_by(half,workerid,condition,trial_type,quantifier,ambiguity_type) %>% 
  summarise(p = mean(clicked))) + geom_errorbar(aes(ymin=p-low, ymax=p+high))


```



```{r model}

contrasts(d$ambiguity_type) <- contr.treatment(5)
contrasts(d$trial_type) <- contr.treatment(8)

summary(glm(formula = clicked ~ ambiguity_type:half + half + trial_type, data = d %>% filter(utterance_label == "quantifier") %>% filter(label == "target") %>% filter(condition == "many_some"), family="binomial"))
summary(glm(formula = clicked ~ ambiguity_type:half + half + trial_type, data = d %>% filter(utterance_label == "quantifier") %>% filter(label == "target") %>% filter(condition == "many_many"), family="binomial"))

```
